from django.contrib import admin
from exerciser.models import ExampleUsageRecord, Document, Fragment, Step, Change, Explanation, Question, Option, Application, Panel, UsageRecord, QuestionRecord, Group, Teacher, Student, AcademicYear, FragmentStyle , Example, HTMLExplanation, HTMLStep, ExampleQuestion, ExampleOption, OptionComment, ExampleStep
admin.site.register(Document)
admin.site.register(Fragment)
admin.site.register(Step)
admin.site.register(Change)
admin.site.register(Explanation)
admin.site.register(Question)
admin.site.register(Option)
admin.site.register(Application)
admin.site.register(Panel)
admin.site.register(UsageRecord)
admin.site.register(QuestionRecord)
admin.site.register(Group)
admin.site.register(Teacher)
admin.site.register(Student)
admin.site.register(AcademicYear)
admin.site.register(FragmentStyle)
admin.site.register(Example)
admin.site.register(HTMLExplanation)
admin.site.register(HTMLStep)
admin.site.register(ExampleQuestion)
admin.site.register(ExampleOption)
admin.site.register(OptionComment)
admin.site.register(ExampleStep)
admin.site.register(ExampleUsageRecord)